apiVersion: apps/v1
kind: Deployment
metadata:  
  name: my-app
  labels:
    service: v1
    type:
spec:
  templates:
    metadata:  
      name: my-app
      labels:
        service: v1
        type:
    containers:
      - image: my-app:latest
        name: my-app
  replicasets: 3
  selectors:
    matachlabels:
      service: v1
      