apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  lables:
    env:
    service:
spec:      #Here in the spec defines what is going to create in the particular object, we need to define POD templates
  templates:
    metadata:
      name: nginx
      labels:
        app: fist
        env: dev
        tier: frontend
    spec:
      containers:
        - name: app
          image: nginx:latest
        - name: backend
          image: backend:latest

  replicas: 3


