apiVersion: v1 ----> string
kind: Pod -------> string
metadata:  #metadata is data about the Object (POD)
  name: my-first-app # all the fields under metadata is dictinary
  labels:
    service: test-servicce
    environment: dev
    app: my-app-pod
spec:  # it is also dictonary
  containers:  #List/arry
    - name: my-first-app  # here - indicates 1st Item in the list
      image: busy-box:latest
    - name: my-backend-app
      image: sql:latest

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: fist
    env: dev
    tier: frontend
spec:
  containers:
    - name: app
      image: nginx:latest
    - name: backend
      image: backend:latest

      

